context:
  version: "10.0.4"

package:
  name: concurrently
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/concurrently/-/concurrently-${{ version }}.tgz
  sha256: e1b0f67677029d6f9686f783e7316a6f2883c1a91cc3299ab7f85ec3b484ee82

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - concurrently --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run commands concurrently.
  homepage: https://github.com/open-cli-tools/concurrently
  repository: https://github.com/open-cli-tools/concurrently

extra:
  recipe-maintainers:
    - danielnachun
