context:
  version: "10.0.0"

package:
  name: concurrently
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/concurrently/-/concurrently-${{ version }}.tgz
  sha256: 1badcfbadae698f438ce7e15989ebce89b74475334f91a3fbc41dc0a2ac6159e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - concurrently --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run commands concurrently.
  homepage: https://github.com/open-cli-tools/concurrently
  repository: https://github.com/open-cli-tools/concurrently

extra:
  recipe-maintainers:
    - danielnachun
