context:
  version: "10.0.1"

package:
  name: concurrently
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/concurrently/-/concurrently-${{ version }}.tgz
  sha256: 747ae53f60c390767e7bbf7a5154ffdd8aadaa83f3ef1325607a916852944a91

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - concurrently --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run commands concurrently.
  homepage: https://github.com/open-cli-tools/concurrently
  repository: https://github.com/open-cli-tools/concurrently

extra:
  recipe-maintainers:
    - danielnachun
